Repository msboffl/data-structures-and-algorithms, pull requests merged in 2022-10, with the labels that each got.

#9 updated changes
  Data Structures/Linked Lists/README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest 2022

#15 Create insertion_sort.py
  Algorithms/Sorting/insertion_sort.py
Labels: good first issue, hacktoberfest, hacktoberfest 2022

#17 Q-1491
  Leetcode/1401-1500/1491. Average Salary Excluding the Minimum and Maximum Salary/Approach 1 (Brute Force).py
Labels: hacktoberfest, hacktoberfest 2022

#18 Add array blog
  Data Structures/Arrays/README.md
Labels: hacktoberfest, hacktoberfest 2022

#19 Add about Linked list
  Data Structures/Linked Lists/README.md
Labels: good first issue, hacktoberfest, hacktoberfest 2022

#21 Create Median of Two Sorted Array.cpp
  Leetcode/Median of Two Sorted Array.cpp
Labels: good first issue, hacktoberfest, hacktoberfest 2022, hacktoberfest-accepted

#23 Create TwoStacks.cpp
  Data Structures/Stacks/TwoStacks.cpp
Labels: good first issue, hacktoberfest, hacktoberfest 2022, hacktoberfest-accepted
